### ISSUE TITLE
Add 'back to the registry' button

### ISSUE THREAD

**Issue by daviddao** [biojs/registry-ui#2]
Until now, we only get back to the overview page by typing a new search. We should link the logo to registry.biojs.net instead of biojs.net and add a "back" button.

**Comment by wilzbach** [comment]
I changed the logo link now twice (it was linked [in october](https://github.com/biojs/registry-ui/commit/3bc68ead435511135589db5f0277e879c6fc7d5b), but you overwrote it ;-))

>  add a "back" button.

Jep it seems that it is non-intuitive to click on the logo or remove the search text to get back

**Comment by wilzbach** [comment]
we should also add a more intuive back arrow somewhere ...

**Comment by wilzbach** [comment]
done in 5f127dd905b55ef64ed10cde692caeb8f7d20f71
