### ISSUE TITLE
delete the master branch

### ISSUE THREAD

**Issue by daviddao** [biojs/registry-ui#3]
Should we delete the master branch or does something/someone depend on it?

**Comment by mhelvens** [comment]
I don't think it's mandatory, as such, to have a `master` branch. But usually main development happens there. Not having one may confuse people.

**Comment by wilzbach** [comment]
As somehow people forget to push in the `master` branch I deleted it temporary (it was not used as main branch), at the moment @daviddao and I are only pushing small design fixs, so therefore we don't need the master. It is not that I would mind to push into two branches, but I have seen other people forgetting it.
However if someone plans to work more extensively on the registry-ui, I would vote for having a master branch again. 

>  Not having one may confuse people.

For pure github pages it is quite common to declare `gh-pages` as master.
