### ISSUE TITLE
Logo.png in repository

### ISSUE THREAD

**Issue by mpschr** [biojs/registry-ui#6]
Hi

Just general input: I think it would be nice if a repository could define a logo.png or something similar which will then be shown rather than the repository owner image.

**Comment by wilzbach** [comment]
For a very short time we experimented with [automatically generated screenshots](http://rawgit.com/biojs/registry-ui/9ec47a32339ac684d291782e79427cc69a7f9bcf/client/index.html#/), but we had some issues with phantomjs. 

> if a repository could define a logo.png

+1 - what about having a field in the `package.json` like `screenshot` or `thumbnail`?

**Comment by mpschr** [comment]
That would be a good solution, using `package.json`. Some may have interest to prepare a nice image with additional legends/explanation rather than a screenshot in initialization state.

A side question: is the `package.json` free format?

**Comment by wilzbach** [comment]
Yep it is, but there is the risk of creating conflicts with other services. However I don't think that anyone else will use the key "thumbnail" or "screenshot" for something different, so this should be fine :) 

Has anyone a personal preference over one of the suggested keys : "screenshot", "thumbnail"? 
I would suggest to use the singular as in most cases only one thumbnail is enough - the registry could accept also an array (and if wanted check for the plural with 's').

**Comment by mpschr** [comment]
Singular is fine and `screenshot` is clear. I don't know what exactly you'd expect with `thumbnail` - a small version of the screenshot?

Personally, I'd like to have the ability to specifiy `logo`.

**Comment by mhelvens** [comment]
I'd say that namespace conflicts are a definite concern. It seems impolite to claim a bunch of common nouns for BioJS. There may be agreed upon standards for top-level keys in package.json. Otherwise, I'd say you should only use a top level `biojs` key, and house everything else under that key.

**Comment by emepyc** [comment]
I would say that "screenshot" is a bit limited. Using a project logo or something like this is another use of this.

**Comment by wilzbach** [comment]
> It seems impolite to claim a bunch of common nouns for BioJS

+1

@mpschr I think we are talking about two different things. You want to change the user avatar with a custom logo? Then I think `avatar` is best?

@emepyc Instead of an automatic generated screenshot the user could provide one (or multiple) screenshots that will be displayed on the registry (as part of the current table view) - this is could be very nice for the card view, too. However then we should also agree on a thumbnail size like 600x400 or 800x600 - I think for now it is a total overkill to specify different thumbnail sizes ...

**Comment by mpschr** [comment]
@greenify Ah yeah I was talking about the avatars. The `logo` would be for those who prefer to put their software logo instead of their _personal_ avatar. This way you could chose, and if nothing is provided the avatar is there.

**Comment by wilzbach** [comment]
@mpschr just add this config to your `package.json` - maybe I find some free time over the weekend ;-)

```
"biojs": {
   "logo": "<path>"
}
```

**Comment by mpschr** [comment]
Ok, I've included it. Let's see if it appears some time ;-)

Best

**Comment by wilzbach** [comment]
The registry appends "logo.png" if no file extension is given ;-)

So I close this issue as this was only about the avatar / logo
