### ISSUE TITLE
Faulty image references in README.md 

### ISSUE THREAD

**Issue by mpschr** [biojs/registry-ui#7]
Hi, 

It's a great idea to re-use the README.md from the repository and show it along with the biojs component. Unfortunately, images are is not displayed, such is the case here: http://registry.biojs.net/client/#/detail/muts-needle-plot

The reason is the image relative path:  `<img src="mutneedles.png" alt="Image of a Needle-Plot">`
- Either create a local copy  
- or refer the link to the original repository: `https://github.com/bbglab/muts-needle-plot/raw/master/mutneedles.png` as in the [npm-repository](https://www.npmjs.com/package/muts-needle-plot)

**Comment by wilzbach** [comment]
Thanks for reporting this problem :-)
