### ISSUE TITLE
should components specify a preferred frame height?

### ISSUE THREAD

**Issue by wilzbach** [biojs/registry-ui#8]
Apparently there are some BioJS components need more spaces than others. Should they be allowed to specify a "wished" frame height - or should they adjust themselves to the default height (currently 400px)?. Actually I would prefer the latter, but I do see that this is just not possible for some components.

A bit of background: `400px` is just a random value (no empirical study made).

**Comment by mhelvens** [comment]
Seems like a good idea to me. Some may need more, some less. 400px could be a fallback.

**Comment by wilzbach** [comment]
With this commit the registry-ui handles `registryHeight` - I have changed this value in one [package](http://registry.biojs.net/client/#/detail/menu-builder).

I just realized that if we ever implement a way (e.g. dropdown menu) to switch the iframe on the detail page, it might be possible that a specific example wants uses more/less space. Currently the concept with snippets is that if you specify a `<example>.json`, you can overwrite the package configs - we could use the same file to overwrite the registryHeight (if ever needed).

FYI I started to [document](https://github.com/biojs/biojs/wiki/BioJS-sections-in-the-package.json) all sections of the `package.json` that we use.

**Comment by mhelvens** [comment]
Perhaps it would be best to abandon `package.json` and instruct packages to
include a `biojs.json` file. You could design the format of that one
however you like.

**Comment by ljgarcia** [comment]
Hi,

What are the pros/cons of a biojs element within the package.json? Like 
the one already proposed
"biojs": {
    "logo": "<path>"
}

by now, we want just the logo, and the screenshot there, right? any 
further ideas that make a biojs.json a better option?

Cheers,

**Comment by timruffles** [comment]
I like the idea of a `biojs` property in the JSON with all the biojs
elements. Self-documenting (people will see and google) and avoids clashes

**Comment by mhelvens** [comment]
Yeah, a `biojs` property in `package.json`, or a `biojs.json` file are both acceptable. This should override anything specified in the top lvl of `package.json`.

Hell, why not go crazy and accept either / both.

**Comment by wilzbach** [comment]
> Perhaps it would be best to abandon `package.json` and instruct packages to include a `biojs.json` file.

I see two main disadvantages about creating a separate file: 

(1) the registry saves the content of package.json directly as json in their couchdb, so we wouldn't have to download a separate file
(2) nearly all npm commands, but especially "npm publish" check the package.json for json error (biojs.json could contain json errors ...)
(3) it would create yet another file - and people are already confused with the amount of files we generate with "slush".

> Hell, why not go crazy and accept either / both.

Nice idea, but (for now) I am lazy :P
One could add another promise to the [github cronjob](https://github.com/biojs/registry-workmen/blob/master/lib/github.js9

> I just realized that if we ever implement a way (e.g. dropdown menu) to switch the iframe on the detail page

This (= the dropdown chooser) is now part of the BioJS reality :)

**Comment by timruffles** [comment]
+1 to keeping to package.json for the reasons above

**Comment by mhelvens** [comment]
Sure. That seems fine.

**Comment by wilzbach** [comment]
"registryHeight" (part of "biojs") is now used - it is documented at the [BioJS wiki](https://github.com/biojs/biojs/wiki/BioJS-sections-in-the-package.json).
